import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Polon League V2</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="flex justify-center items-center flex-col min-h-screen">
        <h1 className="text-6xl font-bold mb-2">Polon League V2</h1>

        <p className="text-4xl">NextJS + Tailwind</p>
      </main>
    </div>
  );
};

export default Home;
